[app]
title = MediaToolSuite
package.name = mediatoolsuite
package.domain = org.mediatoolsuite
source.dir = .
source.include_exts = py,png,jpg,jpeg,gif,ttf,kv
version = 1.0.0
requirements = python3,kivy==2.3.1,kivymd==2.0.1,Pillow,android
orientation = portrait
osx.python_version = 3.11
osx.kivy_version = 2.3.1
fullscreen = 0
android.accept_sdk_license = True
android.api = 34
android.minapi = 21
android.sdk = 34
android.ndk = 27
android.ndk_version = 27
android.gradle_dependencies = 'androidx.core:core:1.12.0'
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,READ_MEDIA_IMAGES,MANAGE_EXTERNAL_STORAGE
android.arch = arm64-v8a
android.allow_backup = True
android.wakelock = False
android.enable_androidx = True
android.add_src =
android.add_libs_arm64 =
android.add_libs_arm =
android.add_libs_x86 =
android.add_libs_x86_64 =
android.add_assets =
android.add_drawables =
android.banned_libs =
android.extra_jars =
android.verify_local_network = True
android.keyalias = mediatoolsuite
android.keystore = ~/.buildozer/keystore/mediatoolsuite.keystore
android.private_storage_backend = internal
android.copy_libs = True
android.google_apikey =
android.store_libs = True
android.use_libregex = True
android.nick_libs = False
android.use_src_regexp = True
android.jar_sdk_ndk = True
android.gradle_build_dir = .gradle
android.allow_src_build = True
android.allow_src_extra =
android.gradle_task = assembleDebug
android.meta_data =
android.window_soft_input_mode = adjustResize
android.add_src_pattern =
android.avoid_arc = True
android.avoid_jnius = False
android.avoid_pyopenssl = False
android.use_sqlite3 = True
android.extra_src =
android.add_res =
android.add_compile_options =
android.add_gradle_repositories =
android.add_product_flavors =
android.add_build_tools =
p4a.local_recipes =
p4a.hook =
p4a.branch = master
p4a.skip_local_build = False
p4a.command_line_flags =
p4a.extra_env_vars =
p4a.android_app_class =
p4a.android_app_icon =
p4a.android_app_icon_adaptive_background = #2c3e50
p4a.android_app_icon_adaptive_foreground =
p4a.android_manifest_application_flags =
p4a.android_components =
extra_jar_args =
extra_aapt_args =
extra_aapt2_args =
extra_compile_args =
extra_install_args =
extra_link_args =
debug = True
debug_symbols = False
